# Numba

_________________________
## *Intro*
_________________________

Numba does something that we may not be used to in typical python

In [2]:
def func_one(n):
    result = 0
    for i in range(n):
        squared = n * n
        result += squared
    return result

def func_two(n):
    result = 0
    squared = n * n
    for i in range(n):
        result += squared
    return result



these two functions demonstrate this
The one core difference is function one has the square calculation inside the for loop and function two calculates it outside the for loop

Let's time the functions


In [3]:
%%timeit
func_one(10000)

833 µs ± 16.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
%%timeit
func_two(10000)

521 µs ± 13.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Let's now make some edits using `numba` and see the performance differences

In [5]:
import numba as nb

@nb.njit
def func_one(n):
    result = 0
    for i in range(n):
        squared = n * n
        result += squared
    return result

@nb.njit
def func_two(n):
    result = 0
    squared = n * n
    for i in range(n):
        result += squared
    return result

func_one(1); func_two(2);

In [6]:
%%timeit
func_one(10000)

140 ns ± 2.82 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [7]:
%%timeit
func_two(10000)

142 ns ± 1.64 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


These now run in nanoseconds instead of microseconds

Both of them are also about the same speed



Numba applies a just-in-time compiler to analyze and convert the functions into more efficient code

* The compiler can make assumptions about the type of variables
* What is happening in the example above is the compiler realizes that the `squared = n * n` in the for loop is just a constant that can be moved outside the loop

_________________________
## *compile*
_________________________

*Not everything is faster!*

When you run this the first time, numba actually makes it slower because it needs to compile

Numba also doesn't know all options for all python code out there, so it can't always improve performance

Numba can only speed up a subset of python code


In [8]:
@nb.njit
def func_test(n):
    result = {}
    for i in range(n):
        new_dict = {'a' * n: n}
        result[squared] = new_dict
    return result

In [9]:
func_test(10)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'squared' is not defined

Numba is built for numeric code so we should limit ourselves to that if we're going to use it

_________________________
## *benchmark*
_________________________

## Numba Settings

In [18]:
import numpy as np

In [19]:
@nb.njit()
def hypot_n(x, y):
    return (x**2 + y**2)**0.5

@nb.njit(parallel=True, fastmath=True)
def hypot_p(x, y):
    return (x**2 + y**2)**0.5

the `parallel=True` flag means that if you pass a numpy array and the operation is parallizable, it will try to use more than one core

the `fastmath` flag is a little more involved. Documentation is [here](https://llvm.org/docs/LangRef.html#fast-math-flags)

In [20]:
r1, r2 = np.random.random(size=(2000, 2000)), np.random.random(size=(2000, 2000))
hypot_n(r1, r2); hypot_p(r1, r2)

array([[0.49733694, 1.03534285, 0.93989041, ..., 0.2836821 , 0.68839745,
        0.64224657],
       [1.37621328, 1.00269571, 0.67004165, ..., 0.85373208, 0.78547239,
        0.86233801],
       [0.04557801, 0.51159555, 0.58555236, ..., 0.06208591, 0.26993877,
        0.68370392],
       ...,
       [0.14040431, 0.99945322, 0.57574555, ..., 0.39669118, 1.21998116,
        0.50143965],
       [0.73949094, 0.68065982, 0.61357355, ..., 0.52962312, 0.17424656,
        0.35544613],
       [0.8973539 , 0.87803393, 0.74318447, ..., 1.18239089, 0.96190928,
        1.17236966]])

In [21]:
%%timeit
hypot_n(r1, r2)

12 ms ± 191 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%%timeit
hypot_p(r1, r2)

8.07 ms ± 51.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Let's see how long this takes without numba

In [23]:
%%timeit
(r1**2 + r2**2)**0.5

27.8 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


We can see that this jit compiler can even be faster than numpy at times

_________________________
## *types*
_________________________

We can speed up the code even more by being explicit about the types of inputs it can accept

In [24]:
from numba import float64

float64[:, :](float64[:, :], float64[:, :])

(array(float64, 2d, A), array(float64, 2d, A)) -> array(float64, 2d, A)

The above signature definition is what we're now feeding as the first argument to the nb decorator

We've imported the float64 type
the above accepts two-dimensional numpy arrays

In [26]:
@nb.njit(float64[:, :](float64[:, :], float64[:, :]), parallel=True, fastmath=True)
def hypot_t(x, y):
    return (x**2 + y**2)**0.5

hypot_t(r1, r2);

In [27]:
%%timeit
hypot_n(r1, r2)

12 ms ± 186 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%timeit
hypot_t(r1, r2)

8.12 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


We again see a speed improvement

_________________________
## *vectorize*
_________________________

## Numpy axes

Functions that have axes allows us to apply funcitons on a specific axis inside an array


In [29]:
arr = np.ones((5, 4)) * 1.01
arr

array([[1.01, 1.01, 1.01, 1.01],
       [1.01, 1.01, 1.01, 1.01],
       [1.01, 1.01, 1.01, 1.01],
       [1.01, 1.01, 1.01, 1.01],
       [1.01, 1.01, 1.01, 1.01]])

In [30]:
arr.cumsum(axis=0)

array([[1.01, 1.01, 1.01, 1.01],
       [2.02, 2.02, 2.02, 2.02],
       [3.03, 3.03, 3.03, 3.03],
       [4.04, 4.04, 4.04, 4.04],
       [5.05, 5.05, 5.05, 5.05]])

This takes the sum vertically down 

In [31]:
arr.cumsum(axis=1)

array([[1.01, 2.02, 3.03, 4.04],
       [1.01, 2.02, 3.03, 4.04],
       [1.01, 2.02, 3.03, 4.04],
       [1.01, 2.02, 3.03, 4.04],
       [1.01, 2.02, 3.03, 4.04]])

This takes the sum horizontally across 

Numba can also take axes as arguments

In [32]:
from numba import vectorize, float64, float32

@vectorize([float64(float64, float64)])
def cumprod(x, y):
    return x * y

this `cumprod` function is now a universal funtion inside numpy

this means we can use it to accumulate along an axis or reduce along an axis

In [33]:
cumprod.accumulate(arr, axis=0)

array([[1.01      , 1.01      , 1.01      , 1.01      ],
       [1.0201    , 1.0201    , 1.0201    , 1.0201    ],
       [1.030301  , 1.030301  , 1.030301  , 1.030301  ],
       [1.04060401, 1.04060401, 1.04060401, 1.04060401],
       [1.05101005, 1.05101005, 1.05101005, 1.05101005]])

In [34]:
cumprod.accumulate(arr, axis=1)

array([[1.01      , 1.0201    , 1.030301  , 1.04060401],
       [1.01      , 1.0201    , 1.030301  , 1.04060401],
       [1.01      , 1.0201    , 1.030301  , 1.04060401],
       [1.01      , 1.0201    , 1.030301  , 1.04060401],
       [1.01      , 1.0201    , 1.030301  , 1.04060401]])

In [35]:
cumprod.reduce(arr, axis=0)

array([1.05101005, 1.05101005, 1.05101005, 1.05101005])

In [36]:
cumprod.reduce(arr, axis=1)

array([1.04060401, 1.04060401, 1.04060401, 1.04060401, 1.04060401])

we can also allow float32

In [37]:
@vectorize([float64(float64, float64),float32(float32, float32)])
def cumprod(x, y):
    return x * y

There are some unsupported types, as well as async functions

documentation is [here](https://numba.pydata.org/numba-doc/dev/reference/pysupported.html)